import { Plus, ShieldCheck, Users } from "lucide-react";
import { Avatar, LegalPage, MetricStrip, PageHeader, PrimaryAction, SectionTitle, StatusTag } from "@/components/legal/legal-ui";

const members = [
  { initials: "MR", name: "Marina Ribeiro", email: "marina@ribeiro.adv.br", role: "Sócia gestora", permission: "Gestão total", cases: 18, deadlines: 3, status: "Ativo" },
  { initials: "CM", name: "Carlos Mendes", email: "carlos@ribeiro.adv.br", role: "Advogado", permission: "Jurídico", cases: 14, deadlines: 5, status: "Ativo" },
  { initials: "AS", name: "Aline Souza", email: "aline@ribeiro.adv.br", role: "Advogada", permission: "Jurídico", cases: 11, deadlines: 2, status: "Ativo" },
  { initials: "LS", name: "Lucas Santos", email: "lucas@ribeiro.adv.br", role: "Paralegal", permission: "Jurídico", cases: 5, deadlines: 1, status: "Ativo" },
  { initials: "PF", name: "Patrícia Freitas", email: "patricia@ribeiro.adv.br", role: "Financeiro", permission: "Financeiro", cases: 0, deadlines: 0, status: "Ativo" },
  { initials: "RB", name: "Rafael Barros", email: "rafael@ribeiro.adv.br", role: "Estagiário", permission: "Leitura atribuída", cases: 4, deadlines: 0, status: "Convidado" },
];

export default function TeamPage() {
  return <LegalPage><PageHeader eyebrow="Escritório / Equipe" title="Equipe e acessos" description="Cargos, distribuição da carteira e permissões efetivas no servidor e no banco." action={<PrimaryAction icon={Plus} href="/painel/equipe?novo=membro">Convidar pessoa</PrimaryAction>} /><MetricStrip items={[{ label: "Pessoas ativas", value: "5" }, { label: "Convites pendentes", value: "1" }, { label: "Casos sem responsável", value: "2", tone: "danger" }, { label: "Prazos por redistribuir", value: "1", tone: "danger" }]} />
    <section className="py-8"><SectionTitle title="Membros do escritório" description="O cargo controla acesso jurídico e financeiro através das políticas RLS" /><div className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[1.2fr_.7fr_.75fr_.4fr_.45fr_.55fr] gap-5 border-y border-white/[0.07] py-3 text-[9px] font-semibold uppercase tracking-[0.09em] text-white/25"><span>Pessoa</span><span>Cargo</span><span>Acesso</span><span>Casos</span><span>Prazos</span><span>Status</span></div>{members.map((member) => <div key={member.email} className="grid grid-cols-[1.2fr_.7fr_.75fr_.4fr_.45fr_.55fr] items-center gap-5 border-b border-white/[0.055] py-4"><div className="flex items-center gap-3"><Avatar initials={member.initials} /><div><p className="text-[12px] font-medium text-white/72">{member.name}</p><p className="mt-1 text-[9px] text-white/28">{member.email}</p></div></div><span className="text-[11px] text-white/45">{member.role}</span><span className="text-[10px] text-white/38">{member.permission}</span><span className="text-[12px] text-white/58">{member.cases}</span><span className="text-[12px] text-white/58">{member.deadlines}</span><StatusTag tone={member.status === "Ativo" ? "success" : "warning"}>{member.status}</StatusTag></div>)}</div></div></section>
    <section className="grid border-t border-white/[0.08] py-8 lg:grid-cols-[1.1fr_.9fr]"><div className="lg:border-r lg:border-white/[0.08] lg:pr-9"><SectionTitle title="Distribuição de trabalho" description="Casos ativos por responsável" /><div className="space-y-5">{[{ name: "Marina Ribeiro", count: 18, width: "88%" }, { name: "Carlos Mendes", count: 14, width: "69%" }, { name: "Aline Souza", count: 11, width: "54%" }, { name: "Lucas Santos", count: 5, width: "25%" }].map((item) => <div key={item.name}><div className="flex justify-between text-[11px]"><span className="text-white/46">{item.name}</span><span className="text-white/62">{item.count}</span></div><div className="mt-2 h-1 bg-white/[0.055]"><div className="h-full bg-od-accent/60" style={{ width: item.width }} /></div></div>)}</div></div><div className="mt-8 lg:mt-0 lg:pl-9"><SectionTitle title="Modelo de autorização" /><div className="flex gap-3"><ShieldCheck size={17} className="mt-0.5 text-od-text-3/65" /><div><p className="text-[12px] font-medium text-white/65">Permissões aplicadas no banco</p><p className="mt-2 text-[10px] leading-relaxed text-white/32">Sócios gestores controlam jurídico e financeiro. Advogados e paralegais gerenciam casos. Financeiro acessa contratos, recebíveis e pagamentos. Estagiários veem apenas casos atribuídos.</p></div></div><div className="mt-6 flex gap-3"><Users size={17} className="mt-0.5 text-white/30" /><div><p className="text-[12px] font-medium text-white/65">Isolamento por organização</p><p className="mt-2 text-[10px] leading-relaxed text-white/32">Todos os registros permanecem vinculados ao org_id e ao workspace law_office.</p></div></div></div></section>
  </LegalPage>;
}
