import { Download, FileCheck2, FilePenLine, FileText, Plus, Search, Signature } from "lucide-react";
import { FeaturedDocumentPreview } from "@/components/legal/featured-document-preview";
import { LegalPage, MetricStrip, PageHeader, PrimaryAction, SectionTitle, StatusTag } from "@/components/legal/legal-ui";

const docs = [
  { name: "Contestação_v3.docx", type: "Petição", caseName: "Construtora Vale × Município", owner: "Carlos Mendes", version: "v3", updated: "Hoje, 11:42", status: "Em revisão", tone: "warning" as const },
  { name: "Procuração_Mariana_Lopes.pdf", type: "Procuração", caseName: "Mariana Lopes × Grupo Atlas", owner: "Marina Ribeiro", version: "v1", updated: "Ontem, 16:10", status: "Assinado", tone: "success" as const },
  { name: "Laudo_pericial_contábil.pdf", type: "Prova", caseName: "Inventário de Paulo Nogueira", owner: "Aline Souza", version: "v1", updated: "15 jul, 09:22", status: "Aprovado", tone: "brand" as const },
  { name: "Réplica_banco_união.docx", type: "Petição", caseName: "Comercial Vértice × Banco União", owner: "Marina Ribeiro", version: "v2", updated: "12 jul, 18:04", status: "Rascunho", tone: "neutral" as const },
];

export default function DocumentsPage() {
  return <LegalPage><PageHeader eyebrow="Jurídico / Documentos" title="Documentos" description="Arquivos dos processos, versões, revisão e assinatura eletrônica." action={<PrimaryAction icon={Plus} href="/painel/juridico/documentos?novo=documento">Novo documento</PrimaryAction>} /><MetricStrip items={[{ label: "Documentos ativos", value: "284" }, { label: "Aguardando revisão", value: "8", tone: "danger" }, { label: "Para assinatura", value: "5" }, { label: "Protocolados em julho", value: "31", tone: "success" }]} />
    <section className="grid border-b border-white/[0.08] lg:grid-cols-[1.55fr_.65fr]"><div className="py-8 lg:border-r lg:border-white/[0.08] lg:pr-9"><div className="flex items-end justify-between"><SectionTitle title="Arquivos recentes" description="Documentos vinculados aos casos que você pode acessar" /><div className="mb-6 flex items-center gap-2 border-b border-white/[0.07] pb-2"><Search size={12} className="text-white/28" /><span className="text-[10px] text-white/28">Buscar arquivo</span></div></div><div>{docs.map((doc) => <div key={doc.name} className="grid grid-cols-[28px_minmax(0,1fr)_70px_90px] items-center gap-4 border-t border-white/[0.06] py-4 first:border-t-0"><FileText size={16} className="text-white/28" /><div className="min-w-0"><p className="truncate text-[12px] font-medium text-white/72">{doc.name}</p><p className="mt-1 truncate text-[10px] text-white/30">{doc.type} · {doc.caseName} · {doc.version}</p></div><StatusTag tone={doc.tone}>{doc.status}</StatusTag><div className="text-right"><p className="text-[9px] text-white/30">{doc.updated}</p><button type="button" aria-label={`Baixar ${doc.name}`} className="mt-2 text-white/24 hover:text-white/60"><Download size={12} /></button></div></div>)}</div></div>
      <aside className="py-8 lg:pl-9"><SectionTitle title="Revisão prioritária" description="Documento com prazo mais próximo" /><FeaturedDocumentPreview /><div className="mt-7 space-y-5 border-t border-white/[0.07] pt-6"><div className="flex gap-3"><FilePenLine size={15} className="mt-0.5 text-amber-300/60" /><div><p className="text-[11px] font-medium text-white/64">8 aguardando revisão</p><p className="mt-1 text-[10px] leading-relaxed text-white/30">3 documentos têm prazo nas próximas 48 horas.</p></div></div><div className="flex gap-3"><Signature size={15} className="mt-0.5 text-violet-300/60" /><div><p className="text-[11px] font-medium text-white/64">5 enviados para assinatura</p><p className="mt-1 text-[10px] leading-relaxed text-white/30">Integração Autentique acompanhando o status.</p></div></div><div className="flex gap-3"><FileCheck2 size={15} className="mt-0.5 text-emerald-300/60" /><div><p className="text-[11px] font-medium text-white/64">12 aprovados nesta semana</p><p className="mt-1 text-[10px] leading-relaxed text-white/30">Versões aprovadas estão bloqueadas para edição.</p></div></div></div></aside>
    </section>
  </LegalPage>;
}
