import { Download, Plus, ReceiptText, WalletCards } from "lucide-react";
import { LegalPage, MetricStrip, PageHeader, PrimaryAction, QuietAction, SectionTitle, StatusTag } from "@/components/legal/legal-ui";

const receivables = [
  { client: "Mariana Lopes", agreement: "Honorários trabalhistas", installment: "4/6", due: "20 jul 2026", original: "R$ 4.000", paid: "R$ 0", balance: "R$ 4.000", status: "Pendente", tone: "warning" as const },
  { client: "Construtora Vale", agreement: "Contencioso mensal", installment: "7/12", due: "15 jul 2026", original: "R$ 8.500", paid: "R$ 0", balance: "R$ 8.500", status: "Vencido", tone: "danger" as const },
  { client: "Comercial Vértice", agreement: "Revisão contratual", installment: "2/3", due: "12 jul 2026", original: "R$ 6.000", paid: "R$ 3.000", balance: "R$ 3.000", status: "Parcial", tone: "brand" as const },
  { client: "Paulo Nogueira", agreement: "Inventário e partilha", installment: "3/8", due: "10 jul 2026", original: "R$ 5.200", paid: "R$ 5.200", balance: "R$ 0", status: "Pago", tone: "success" as const },
];

export default function FinancePage() {
  return <LegalPage><PageHeader eyebrow="Escritório / Financeiro" title="Financeiro jurídico" description="Contratos de honorários, recebíveis, pagamentos, despesas e valores pertencentes ao cliente." action={<><QuietAction icon={Download} href="/api/reports/deals">Exportar</QuietAction><PrimaryAction icon={Plus} href="/painel/financeiro?novo=lancamento">Novo lançamento</PrimaryAction></>} /><MetricStrip items={[{ label: "Recebíveis contratados", value: "R$ 84,5 mil", note: "12 parcelas" }, { label: "Recebido em julho", value: "R$ 38,2 mil", note: "+9,4%", tone: "success" }, { label: "Recebíveis vencidos", value: "R$ 12,8 mil", note: "4 cobranças", tone: "danger" }, { label: "Despesas a reembolsar", value: "R$ 6,4 mil", note: "17 itens" }]} />
    <section className="grid border-b border-white/[0.08] xl:grid-cols-[1.6fr_.7fr]"><div className="py-8 xl:border-r xl:border-white/[0.08] xl:pr-9"><SectionTitle title="Recebíveis" description="Parcelas geradas por contratos de honorários ativos" /><div className="overflow-x-auto"><div className="min-w-[820px]"><div className="grid grid-cols-[1.1fr_1.15fr_.4fr_.65fr_.6fr_.6fr_.55fr] gap-4 border-y border-white/[0.07] py-3 text-[9px] font-semibold uppercase tracking-[0.08em] text-white/25"><span>Cliente</span><span>Contrato</span><span>Parcela</span><span>Vencimento</span><span>Valor</span><span>Saldo</span><span>Status</span></div>{receivables.map((item) => <div key={`${item.client}-${item.installment}`} className="grid grid-cols-[1.1fr_1.15fr_.4fr_.65fr_.6fr_.6fr_.55fr] items-center gap-4 border-b border-white/[0.055] py-4"><span className="text-[11px] font-medium text-white/72">{item.client}</span><span className="text-[10px] text-white/38">{item.agreement}</span><span className="text-[10px] text-white/38">{item.installment}</span><span className="text-[10px] text-white/38">{item.due}</span><span className="text-[11px] text-white/56">{item.original}</span><span className={`text-[11px] ${item.tone === "danger" ? "text-[#ff8175]" : "text-white/56"}`}>{item.balance}</span><StatusTag tone={item.tone}>{item.status}</StatusTag></div>)}</div></div></div>
      <aside className="py-8 xl:pl-9"><SectionTitle title="Composição do mês" /><div className="space-y-6"><div><div className="flex items-center justify-between text-[11px]"><span className="text-white/42">Honorários fixos</span><span className="text-white/68">R$ 27.400</span></div><div className="mt-2 h-1 bg-white/[0.06]"><div className="h-full w-[72%] bg-violet-400/70" /></div></div><div><div className="flex items-center justify-between text-[11px]"><span className="text-white/42">Honorários de êxito</span><span className="text-white/68">R$ 7.800</span></div><div className="mt-2 h-1 bg-white/[0.06]"><div className="h-full w-[42%] bg-violet-400/50" /></div></div><div><div className="flex items-center justify-between text-[11px]"><span className="text-white/42">Consultas</span><span className="text-white/68">R$ 3.000</span></div><div className="mt-2 h-1 bg-white/[0.06]"><div className="h-full w-[24%] bg-violet-400/35" /></div></div></div><div className="mt-8 border-t border-white/[0.07] pt-6"><p className="flex items-center gap-2 text-[11px] font-medium text-white/58"><WalletCards size={13} />Valores do cliente</p><p className="mt-2 text-[10px] leading-relaxed text-white/30">R$ 18.400 mantidos separadamente. Esses valores não compõem receita do escritório.</p></div></aside>
    </section>
    <section id="despesas" className="scroll-mt-20 py-8"><SectionTitle title="Despesas recentes" description="Custas, diligências, perícias e despesas reembolsáveis" action={<QuietAction icon={ReceiptText} href="#despesas">Ver todas</QuietAction>} /><div className="grid gap-x-8 lg:grid-cols-2">{[{ title: "Custas de distribuição", caseName: "Comercial Vértice × Banco União", value: "R$ 742", status: "A reembolsar" }, { title: "Honorários periciais", caseName: "Inventário de Paulo Nogueira", value: "R$ 2.400", status: "A reembolsar" }, { title: "Correspondente em Belo Horizonte", caseName: "Construtora Vale × Município", value: "R$ 680", status: "Reembolsado" }, { title: "Emolumentos cartorários", caseName: "Mariana Lopes × Grupo Atlas", value: "R$ 318", status: "Reembolsado" }].map((expense) => <div key={expense.title} className="flex items-center justify-between gap-4 border-t border-white/[0.06] py-4"><div><p className="text-[11px] font-medium text-white/66">{expense.title}</p><p className="mt-1 text-[10px] text-white/28">{expense.caseName}</p></div><div className="text-right"><p className="text-[11px] text-white/62">{expense.value}</p><p className="mt-1 text-[9px] text-white/28">{expense.status}</p></div></div>)}</div></section>
  </LegalPage>;
}
