import Link from "next/link";
import { CalendarDays, ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { LegalPage, MetricStrip, PageHeader, PrimaryAction, QuietAction, SectionTitle, StatusTag } from "@/components/legal/legal-ui";

const days = [
  { day: "Seg", date: "14", items: [{ time: "09:30", title: "Revisão de documentos", type: "Interno" }] },
  { day: "Ter", date: "15", items: [{ time: "14:00", title: "Reunião · Comercial Vértice", type: "Cliente" }, { time: "17:00", title: "Enviar réplica", type: "Prazo" }] },
  { day: "Qua", date: "16", items: [{ time: "10:30", title: "Audiência · Grupo Atlas", type: "Audiência" }] },
  { day: "Qui", date: "17", items: [{ time: "15:00", title: "Reunião de equipe", type: "Interno" }] },
  { day: "Sex", date: "18", current: true, items: [{ time: "10:30", title: "Audiência · Mariana Lopes", type: "Audiência" }, { time: "17:00", title: "Protocolar contestação", type: "Prazo" }] },
];

export default async function AgendaPage(props: { searchParams?: Promise<{ semana?: string }> }) {
  const searchParams = await props.searchParams;
  const weekTitle = searchParams?.semana === "anterior" ? "Semana de 7 a 11 de julho" : searchParams?.semana === "proxima" ? "Semana de 21 a 25 de julho" : "Semana de 14 a 18 de julho";
  return <LegalPage><PageHeader eyebrow="Jurídico / Agenda e prazos" title="Agenda jurídica" description="Prazos processuais, audiências, compromissos internos e solicitações de clientes." action={<><QuietAction icon={CalendarDays} href="/painel/juridico/prazos/calculadora">Calcular prazo</QuietAction><PrimaryAction icon={Plus} href="/painel/juridico/prazos?novo=prazo">Novo compromisso</PrimaryAction></>} /><MetricStrip items={[{ label: "Prazos nesta semana", value: "7", note: "3 concluídos" }, { label: "Vencem hoje", value: "2", tone: "danger" }, { label: "Audiências", value: "4", note: "2 online" }, { label: "Sem responsável", value: "1", tone: "danger" }]} />
    <section className="py-8"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><SectionTitle title={weekTitle} description="Horário de Brasília · feriados forenses considerados" /><div className="mb-6 flex items-center gap-1"><QuietAction icon={ChevronLeft} href="/painel/juridico/prazos?semana=anterior">Anterior</QuietAction><QuietAction icon={CalendarDays} href="/painel/juridico/prazos">Hoje</QuietAction><QuietAction icon={ChevronRight} href="/painel/juridico/prazos?semana=proxima">Próxima</QuietAction></div></div>
      <div className="grid border-y border-white/[0.08] md:grid-cols-5">{days.map((day) => <div key={day.date} className={`min-h-64 border-t border-white/[0.07] p-4 first:border-t-0 md:border-l md:border-t-0 md:first:border-l-0 ${day.current ? "bg-violet-400/[0.025]" : ""}`}><div className="flex items-center justify-between"><span className="text-[11px] font-medium text-white/38">{day.day}</span><span className={`grid size-7 place-items-center text-[12px] ${day.current ? "bg-violet-500 text-white" : "text-white/42"}`}>{day.date}</span></div><div className="mt-5 space-y-5">{day.items.map((item) => <Link key={`${item.time}-${item.title}`} href={{ pathname: "/painel/juridico/prazos", query: { detalhe: item.title, horario: item.time, tipo: item.type } }} className="w-full border-l border-white/[0.1] pl-3 text-left hover:border-violet-400"><span className="text-[9px] text-white/28">{item.time}</span><span className="mt-1.5 block text-[11px] font-medium leading-snug text-white/65">{item.title}</span><span className="mt-2 block text-[9px] text-white/28">{item.type}</span></Link>)}</div></div>)}</div>
    </section>
    <section className="border-t border-white/[0.08] py-8"><SectionTitle title="Próximos prazos" description="Contagem e prioridade operacional" /><div className="grid gap-x-8 lg:grid-cols-2">{[{ title: "Protocolar contestação", caseName: "Construtora Vale × Município", due: "Hoje, 17:00", tone: "danger" as const }, { title: "Manifestação sobre laudo", caseName: "Inventário de Paulo Nogueira", due: "21 jul, 12:00", tone: "warning" as const }, { title: "Enviar documentos ao cliente", caseName: "Comercial Vértice × Banco União", due: "23 jul, 16:00", tone: "neutral" as const }, { title: "Interpor recurso ordinário", caseName: "Helena Costa × INSS", due: "29 jul, 18:00", tone: "neutral" as const }].map((item) => <div key={item.title} className="flex items-center justify-between gap-4 border-t border-white/[0.06] py-4"><div><p className="text-[12px] font-medium text-white/70">{item.title}</p><p className="mt-1 text-[10px] text-white/30">{item.caseName}</p></div><StatusTag tone={item.tone}>{item.due}</StatusTag></div>)}</div></section>
  </LegalPage>;
}
