import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, Building2, CircleUserRound, Handshake, Home, PackageSearch, Scale, Store, Tractor } from "lucide-react";
import { PROFESSION_OPTIONS, type ProfessionType } from "@/lib/professions";

const icons: Record<Exclude<ProfessionType, "founder">, typeof Scale> = { autonomous_seller: Handshake, law_office: Scale, real_estate_broker: Home, service_provider: BriefcaseBusiness, consultant: CircleUserRound, freelancer: PackageSearch, livestock_producer: Tractor, small_business: Store, other: Building2 };
const notes: Record<Exclude<ProfessionType, "founder">, string> = { autonomous_seller: "Vendas, propostas e follow-ups", law_office: "Casos, prazos e operação jurídica", real_estate_broker: "Imóveis, visitas e propostas", service_provider: "Clientes, serviços e agenda", consultant: "Projetos, contratos e entregas", freelancer: "Trabalhos, clientes e recebimentos", livestock_producer: "Carteira rural e negociações", small_business: "Operação comercial e relacionamento", other: "Workspace configurável para sua operação" };

export default function WorkspacesPage() {
  return <main className="mx-auto w-full max-w-[1480px] px-5 pb-20 pt-10 md:px-9 md:pt-14"><header className="max-w-3xl"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-violet-300/55">Plataforma OtimizIA</p><h1 className="mt-4 text-[32px] font-semibold tracking-[-0.035em] text-white/92 md:text-[40px]">Escolha o contexto de trabalho</h1><p className="mt-3 max-w-2xl text-[13px] leading-6 text-white/38">A base da plataforma é compartilhada. Cada profissão recebe linguagem, métricas, funil e ferramentas próprias; advocacia é apenas uma dessas verticais.</p></header><section className="mt-12 grid border-l border-t border-white/[0.08] sm:grid-cols-2 xl:grid-cols-3">{PROFESSION_OPTIONS.map((option) => { const key = option.value as Exclude<ProfessionType, "founder">; const Icon = icons[key]; const href = key === "law_office" ? "/painel/juridico" : `/painel/workspaces/${key}`; return <Link key={key} href={href} className="group min-h-48 border-b border-r border-white/[0.08] p-6 transition-colors hover:bg-white/[0.025]"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center text-violet-300/65"><Icon size={21} strokeWidth={1.6} /></span><ArrowUpRight size={14} className="text-white/20 transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-violet-300/60" /></div><h2 className="mt-7 text-[16px] font-semibold text-white/74">{option.label}</h2><p className="mt-2 text-[11px] text-white/30">{notes[key]}</p></Link>; })}</section></main>;
}

