import Link from "next/link";
import { PendingButton } from "@/components/ui/PendingButton";
import { canViewFinance, outstandingCents, receivableState } from "@/lib/law/law-office";
import { formatBRL } from "@/lib/utils/format";
import { getActiveOrgId, getOrgRole } from "@/lib/workspace/org";
import { createClient } from "@/lib/supabase/server";
import type { Contact, LegalCase, LegalExpense, Receivable } from "@/lib/supabase/types";
import { getWorkspaceKey } from "@/lib/workspace/workspaces";
import { IconAlert, IconCheckCircle, IconPlus, IconWallet } from "../icons";
import { createFeeAgreement, createLegalExpense, recordReceivablePayment, toggleLegalExpenseReimbursed } from "../juridico/actions";

const EXPENSE_CATEGORY_LABEL: Record<string, string> = { court_fee: "Custas judiciais", travel: "Deslocamento", registry: "Cartório", expert: "Perícia", correspondent: "Correspondente", copy: "Cópias", other: "Outro" };

export default async function FinancePage(props: { searchParams: Promise<{ receive?: string }> }) {
  const searchParams = await props.searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const [{ data: profile }, orgId] = await Promise.all([supabase.from("profiles").select("profession_type,is_admin").maybeSingle(), getActiveOrgId(supabase, user!.id)]);
  if (getWorkspaceKey(profile?.profession_type, user?.user_metadata?.profession_type, profile?.is_admin) !== "law_office") return <NotLawOffice/>;
  const [orgRole, { data: membership }] = await Promise.all([getOrgRole(supabase, orgId, user!.id), supabase.from("organization_members").select("job_role").eq("org_id", orgId).eq("user_id", user!.id).maybeSingle()]);
  const isAdmin = orgRole === "admin";
  if (!canViewFinance(membership?.job_role, isAdmin)) return <AccessDenied/>;
  const monthStart = new Date();monthStart.setDate(1);monthStart.setHours(0, 0, 0, 0);
  const [{ data: receivableRows }, { data: contacts }, { data: cases }, { data: payments }, { data: expenseRows }] = await Promise.all([
    supabase.from("receivables").select("*").eq("org_id", orgId).order("due_date"),
    supabase.from("contacts").select("id,name").eq("org_id", orgId).eq("workspace_key", "law_office").order("name"),
    supabase.from("legal_cases").select("id,title").eq("org_id", orgId).order("title"),
    supabase.from("receivable_payments").select("amount_cents").eq("org_id", orgId).gte("paid_at", monthStart.toISOString()),
    supabase.from("legal_expenses").select("*").eq("org_id", orgId).order("expense_date", { ascending: false }),
  ]);
  const receivables = (receivableRows ?? []) as Receivable[];
  const allContacts = (contacts ?? []) as Pick<Contact, "id" | "name">[];
  const allCases = (cases ?? []) as Pick<LegalCase, "id" | "title">[];
  const expenses = (expenseRows ?? []) as LegalExpense[];
  const contactNames = new Map(allContacts.map((item) => [item.id, item.name]));
  const caseTitles = new Map(allCases.map((item) => [item.id, item.title]));
  const open = receivables.filter((item) => item.status !== "paid" && item.status !== "cancelled");
  const overdue = open.filter((item) => receivableState(item) === "overdue");
  const paidThisMonth = (payments ?? []).reduce((sum, item) => sum + (item.amount_cents ?? 0), 0);
  const openCents = open.reduce((sum, item) => sum + outstandingCents(item), 0);
  const overdueCents = overdue.reduce((sum, item) => sum + outstandingCents(item), 0);
  const openReimbursableCents = expenses.filter((item) => item.reimbursable && !item.reimbursed).reduce((sum, item) => sum + item.amount_cents, 0);
  const selected = searchParams.receive ? receivables.find((item) => item.id === searchParams.receive) : null;

  return <div className="ui-page">
    <header className="flex flex-col gap-4 pb-5 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-xs font-semibold text-od-text-3">Financeiro / Honorários</h1><p className="mt-1 max-w-2xl text-sm leading-relaxed text-white/52">Receita do escritório separada de reembolsos e valores pertencentes ao cliente.</p></div><div className="flex flex-wrap gap-2"><Link href="/financeiro/importar" className="inline-flex min-h-11 items-center rounded-md border border-white/[0.1] px-4 text-xs font-semibold text-white/62 hover:bg-white/[0.04] hover:text-white">Importar CSV</Link><Link href="/juridico/processos" className="inline-flex min-h-11 items-center rounded-md bg-od-accent px-4 text-[13px] font-semibold hover:bg-brand-600">Ver processos</Link></div></header>

    <section className="od-band grid sm:grid-cols-2 xl:grid-cols-5"><Metric label="A receber" value={formatBRL(openCents)} icon={IconWallet}/><Metric label="Vencido" value={formatBRL(overdueCents)} icon={IconAlert} danger/><Metric label="Recebido no mês" value={formatBRL(paidThisMonth)} icon={IconCheckCircle}/><Metric label="Contas pendentes" value={String(open.length)} icon={IconWallet}/><Metric label="A reembolsar" value={formatBRL(openReimbursableCents)} icon={IconWallet}/></section>

    <section id="honorarios" className="panel p-5"><SectionHeading icon={IconPlus} title="Novo contrato de honorários" description="Ao salvar, o OtimizIA gera as parcelas automaticamente."/><form action={createFeeAgreement} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><TextField name="title" label="Contrato / serviço" required placeholder="Ex.: Honorários trabalhistas" className="xl:col-span-2"/><Select name="contact_id" label="Cliente" options={allContacts.map((item) => ({ value: item.id, label: item.name }))} required/><Select name="case_id" label="Caso vinculado" options={allCases.map((item) => ({ value: item.id, label: item.title }))}/><Select name="fee_type" label="Modalidade" defaultValue="fixed" options={[{ value: "fixed", label: "Valor fixo" }, { value: "recurring", label: "Mensal" }, { value: "stage", label: "Por etapa" }, { value: "hourly", label: "Por hora" }, { value: "success", label: "Êxito" }, { value: "consultation", label: "Consulta" }]}/><TextField name="total" label="Valor contratado (R$)" placeholder="0,00"/><TextField name="installments" label="Parcelas" type="number" defaultValue="1"/><TextField name="first_due_date" label="1º vencimento" type="date"/><TextField name="success_percent" label="Percentual de êxito" type="number" placeholder="Ex.: 20"/><TextField name="success_basis" label="Base do êxito" placeholder="Ex.: valor recebido"/><TextField name="signed_at" label="Assinado em" type="date"/><div className="md:col-span-2 xl:col-span-4"><label className="label" htmlFor="agreement-notes">Observações</label><textarea id="agreement-notes" name="notes" rows={2} maxLength={1600} className="field mt-1.5 min-h-20 resize-y" placeholder="Condições especiais, forma de cobrança, responsabilidades..."/></div><div className="md:col-span-2 xl:col-span-4"><PendingButton className="btn" pendingLabel="Gerando parcelas"><IconPlus className="h-4 w-4"/>Criar contrato e parcelas</PendingButton></div></form></section>

    {selected ? <section className="rounded-[var(--radius-panel)] border border-od-accent/25 bg-od-accent/[0.06] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-od-text-2">Registrar recebimento</p><h2 className="mt-1 text-[16px] font-semibold">{selected.description}</h2><p className="mt-1 text-xs text-od-text-3">Saldo: {formatBRL(outstandingCents(selected))}</p></div><Link href="/financeiro#recebiveis" className="text-xs text-od-text-3 hover:text-white">Fechar</Link></div><form action={recordReceivablePayment} className="mt-4 grid gap-3 md:grid-cols-4"><input type="hidden" name="receivable_id" value={selected.id}/><TextField name="amount" label="Valor recebido (R$)" required placeholder="0,00"/><Select name="method" label="Forma" defaultValue="pix" options={[{ value: "pix", label: "Pix" }, { value: "boleto", label: "Boleto" }, { value: "transfer", label: "Transferência" }, { value: "card", label: "Cartão" }, { value: "cash", label: "Dinheiro" }, { value: "other", label: "Outro" }]}/><TextField name="paid_at" label="Data e hora" type="datetime-local"/><TextField name="reference" label="Referência" placeholder="Id. do Pix, banco..."/><div className="md:col-span-4"><PendingButton className="btn" pendingLabel="Registrando">Confirmar recebimento</PendingButton></div></form></section> : null}

    <section id="recebiveis" className="panel overflow-hidden"><TableHeading title="Contas a receber" description="Saldo, vencimento e baixa sem misturar com propostas." count={receivables.length}/>{receivables.length === 0 ? <Empty/> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-white/[0.07] text-xs uppercase tracking-wide text-od-text-3"><tr><th className="px-5 py-3 font-semibold">Descrição</th><th className="px-4 py-3 font-semibold">Cliente</th><th className="px-4 py-3 font-semibold">Vencimento</th><th className="px-4 py-3 font-semibold">Saldo</th><th className="px-4 py-3 font-semibold">Situação</th><th className="px-5 py-3"/></tr></thead><tbody>{receivables.map((item) => { const state = receivableState(item); return <tr key={item.id} className="border-b border-white/[0.06] hover:bg-white/[0.025]"><td className="px-5 py-4"><p className="max-w-[18rem] truncate text-[12px] font-semibold">{item.description}</p><p className="mt-1 text-xs text-od-text-3">{item.category === "client_funds" ? "Valor do cliente" : "Receita do escritório"}</p></td><td className="px-4 py-4 text-xs text-white/55">{item.contact_id ? contactNames.get(item.contact_id) ?? "Cliente removido" : "—"}</td><td className={`px-4 py-4 text-xs font-semibold ${state === "overdue" ? "text-[#fb7767]" : "text-white/55"}`}>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.due_date}T12:00:00`))}</td><td className="px-4 py-4 text-xs font-semibold">{formatBRL(outstandingCents(item))}</td><td className="px-4 py-4"><State state={state}/></td><td className="px-5 py-4 text-right">{state !== "paid" && state !== "cancelled" ? <Link href={`/financeiro?receive=${item.id}`} className="rounded-md border border-white/[0.1] px-3 py-2 text-xs font-semibold text-od-accent hover:bg-white/[0.04]">Receber</Link> : null}</td></tr>; })}</tbody></table></div>}</section>

    <section id="despesas" className="panel p-5"><SectionHeading icon={IconPlus} title="Nova despesa" description="Custas, deslocamento e gastos do escritório ou do caso."/><form action={createLegalExpense} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><TextField name="description" label="Descrição" required placeholder="Ex.: Custas de distribuição" className="xl:col-span-2"/><Select name="category" label="Categoria" defaultValue="court_fee" options={Object.entries(EXPENSE_CATEGORY_LABEL).map(([value, label]) => ({ value, label }))}/><TextField name="amount" label="Valor (R$)" required placeholder="0,00"/><Select name="case_id" label="Caso vinculado" options={allCases.map((item) => ({ value: item.id, label: item.title }))}/><TextField name="expense_date" label="Data" type="date"/><label className="flex items-center gap-2 self-end pb-2.5 text-[12px] text-white/60"><input type="checkbox" name="reimbursable" defaultChecked/>Reembolsável</label><div className="md:col-span-2 xl:col-span-4"><label className="label" htmlFor="expense-notes">Observações</label><textarea id="expense-notes" name="notes" rows={2} maxLength={1600} className="field mt-1.5 min-h-20 resize-y"/></div><div className="md:col-span-2 xl:col-span-4"><PendingButton className="btn" pendingLabel="Registrando"><IconPlus className="h-4 w-4"/>Registrar despesa</PendingButton></div></form></section>

    <section className="panel overflow-hidden"><TableHeading title="Despesas" description="Reembolsos pendentes permanecem destacados." count={expenses.length}/>{expenses.length === 0 ? <div className="p-8 text-center"><IconWallet className="mx-auto h-7 w-7 text-od-text-3"/><p className="mt-3 text-[12px] font-semibold">Nenhuma despesa registrada.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-white/[0.07] text-xs uppercase tracking-wide text-od-text-3"><tr><th className="px-5 py-3 font-semibold">Descrição</th><th className="px-4 py-3 font-semibold">Caso</th><th className="px-4 py-3 font-semibold">Data</th><th className="px-4 py-3 font-semibold">Valor</th><th className="px-4 py-3 font-semibold">Reembolso</th><th className="px-5 py-3"/></tr></thead><tbody>{expenses.map((item) => <tr key={item.id} className="border-b border-white/[0.06] hover:bg-white/[0.025]"><td className="px-5 py-4"><p className="max-w-[18rem] truncate text-[12px] font-semibold">{item.description}</p><p className="mt-1 text-xs text-od-text-3">{EXPENSE_CATEGORY_LABEL[item.category]}</p></td><td className="px-4 py-4 text-xs text-white/55">{item.case_id ? caseTitles.get(item.case_id) ?? "Caso removido" : "—"}</td><td className="px-4 py-4 text-xs text-white/55">{new Intl.DateTimeFormat("pt-BR").format(new Date(`${item.expense_date}T12:00:00`))}</td><td className="px-4 py-4 text-xs font-semibold">{formatBRL(item.amount_cents)}</td><td className="px-4 py-4"><span className={`rounded-md px-2 py-1 text-xs font-semibold ${item.reimbursable ? item.reimbursed ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300" : "bg-white/[0.05] text-od-text-3"}`}>{item.reimbursable ? item.reimbursed ? "Reembolsado" : "Pendente" : "Não reembolsável"}</span></td><td className="px-5 py-4 text-right">{item.reimbursable ? <form action={toggleLegalExpenseReimbursed}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="reimbursed" value={String(item.reimbursed)}/><PendingButton className="rounded-md border border-white/[0.1] px-3 py-2 text-xs font-semibold text-od-accent hover:bg-white/[0.04]" pendingLabel="Salvando">{item.reimbursed ? "Desfazer" : "Marcar reembolsado"}</PendingButton></form> : null}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}

function Metric({ label, value, icon: Icon, danger = false }: { label: string; value: string; icon: (p: { className?: string }) => React.ReactElement; danger?: boolean }) { return <article className="flex items-center gap-3 border-b border-white/[0.08] px-4 py-4 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><Icon className={`h-4 w-4 ${danger ? "text-[#fb7767]" : "text-od-text-3"}`}/><div><p className="text-xs text-od-text-3">{label}</p><p className="mt-1 text-[18px] font-bold tracking-[-.03em]">{value}</p></div></article>; }
function SectionHeading({ icon: Icon, title, description }: { icon: (p: { className?: string }) => React.ReactElement; title: string; description: string }) { return <div className="mb-5 flex items-center gap-3 pb-4"><span className="grid size-9 place-items-center rounded-md bg-white/[0.06] text-od-text-2"><Icon className="h-4 w-4"/></span><div><h2 className="text-base font-semibold">{title}</h2><p className="mt-1 text-xs text-white/52">{description}</p></div></div>; }
function TableHeading({ title, description, count }: { title: string; description: string; count: number }) { return <div className="flex items-center justify-between border-b border-white/[0.08] px-5 py-4"><div><h2 className="text-base font-semibold">{title}</h2><p className="mt-1 text-xs text-white/52">{description}</p></div><span className="text-xs text-od-text-3">{count} lançamentos</span></div>; }
function State({ state }: { state: "paid" | "cancelled" | "overdue" | "partial" | "pending" }) { const labels = { paid: "Recebido", cancelled: "Cancelado", overdue: "Vencido", partial: "Parcial", pending: "A vencer" }; const colors = { paid: "bg-emerald-400/10 text-emerald-300", cancelled: "bg-white/[0.05] text-od-text-3", overdue: "bg-red-400/10 text-[#fb7767]", partial: "bg-amber-400/10 text-amber-300", pending: "bg-white/[0.06] text-od-text-2" }; return <span className={`rounded-md px-2 py-1 text-xs font-semibold ${colors[state]}`}>{labels[state]}</span>; }
function TextField({ name, label, type = "text", required = false, placeholder, defaultValue, className = "" }: { name: string; label: string; type?: string; required?: boolean; placeholder?: string; defaultValue?: string; className?: string }) { return <label className={`block ${className}`}><span className="label">{label}{required ? <><span className="ml-1 text-od-text-2">*</span><span className="sr-only"> obrigatório</span></> : null}</span><input name={name} type={type} required={required} maxLength={type === "text" ? 180 : undefined} defaultValue={defaultValue} placeholder={placeholder} className="field mt-1.5"/></label>; }
function Select({ name, label, options, defaultValue, required = false }: { name: string; label: string; options: { value: string; label: string }[]; defaultValue?: string; required?: boolean }) { return <label className="block"><span className="label">{label}{required ? <><span className="ml-1 text-od-text-2">*</span><span className="sr-only"> obrigatório</span></> : null}</span><select name={name} defaultValue={defaultValue ?? ""} required={required} className="field mt-1.5"><option value="">Selecione</option>{options.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>; }
function AccessDenied() { return <section className="panel max-w-xl p-6"><p className="text-xs font-semibold text-od-text-3">Acesso restrito</p><h1 className="mt-2 text-xl font-semibold">Seu cargo não acessa o financeiro.</h1><p className="mt-2 text-[12px] text-od-text-3">Um sócio administrador pode atribuir o cargo Financeiro à sua conta.</p></section>; }
function NotLawOffice() { return <section className="panel max-w-xl p-6"><h1 className="text-xl font-semibold">Financeiro jurídico disponível no workspace de advocacia.</h1><Link href="/painel" className="btn mt-4">Voltar ao painel</Link></section>; }
function Empty() { return <div className="p-8 text-center"><IconWallet className="mx-auto h-7 w-7 text-od-text-3"/><p className="mt-3 text-[12px] font-semibold">Nenhuma conta a receber.</p><p className="mt-1 text-xs text-od-text-3">Crie um contrato de honorários para gerar as parcelas automaticamente.</p></div>; }
