"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, FileText, MessageSquare, Search, Scale, User, X } from "lucide-react";

const results = [
  { icon: Scale, label: "Mariana Lopes × Grupo Atlas", note: "Processo 1008421-22.2026.5.02.0031", href: "/painel/juridico/processos" },
  { icon: User, label: "Mariana Lopes", note: "Cliente · Trabalhista", href: "/painel/contatos" },
  { icon: FileText, label: "Contestação - Grupo Atlas.pdf", note: "Documento · v3", href: "/painel/juridico/documentos" },
];

export function LegalHeaderActions() {
  const [panel, setPanel] = useState<"search" | "messages" | "notifications" | null>(null); const [query, setQuery] = useState("");
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPanel("search"); } if (event.key === "Escape") setPanel(null); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  const filtered = results.filter((item) => `${item.label} ${item.note}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <button type="button" onClick={() => setPanel("search")} className="flex min-w-0 flex-1 items-center gap-2 px-4 text-left md:px-7"><Search size={14} className="text-white/32" /><span className="truncate text-[12px] text-white/34">Buscar processo, cliente ou documento</span><span className="ml-auto hidden text-[10px] text-white/22 md:block">Ctrl K</span></button>
    <div className="flex h-full border-l border-white/[0.07]"><button type="button" onClick={() => setPanel("messages")} aria-label="Mensagens" className="grid size-14 place-items-center border-l border-white/[0.07] text-white/36 hover:bg-white/[0.03] hover:text-white/70"><MessageSquare size={15} /></button><button type="button" onClick={() => setPanel("notifications")} aria-label="Notificações" className="relative grid size-14 place-items-center border-l border-white/[0.07] text-white/36 hover:bg-white/[0.03] hover:text-white/70"><Bell size={15} /><span className="absolute right-4 top-4 size-1 rounded-full bg-[#ff7468]" /></button></div>
    {panel ? <div className="fixed inset-0 z-[90] bg-black/55 pt-20 backdrop-blur-[2px]" onMouseDown={(event) => { if (event.target === event.currentTarget) setPanel(null); }}><section className="mx-auto w-[calc(100%-32px)] max-w-2xl border border-white/[0.09] bg-[#151218] shadow-2xl"><header className="flex h-14 items-center border-b border-white/[0.08] px-5">{panel === "search" ? <><Search size={15} className="text-white/30" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Digite para buscar…" className="h-full min-w-0 flex-1 bg-transparent px-3 text-[12px] text-white/75 outline-none placeholder:text-white/22" /></> : <h2 className="text-[13px] font-semibold text-white/72">{panel === "messages" ? "Mensagens" : "Notificações"}</h2>}<button type="button" onClick={() => setPanel(null)} className="ml-auto grid size-8 place-items-center text-white/30 hover:text-white/65"><X size={15} /></button></header><div className="max-h-[430px] overflow-y-auto p-3">{panel === "search" ? filtered.map(({ icon: Icon, ...item }) => <Link key={item.href} href={item.href} onClick={() => setPanel(null)} className="flex items-center gap-4 px-3 py-3 hover:bg-white/[0.035]"><Icon size={15} className="text-od-text-3" /><span><span className="block text-[11px] font-medium text-white/68">{item.label}</span><span className="mt-1 block text-[9px] text-white/28">{item.note}</span></span></Link>) : panel === "messages" ? <><Link href="/painel/assistente" onClick={() => setPanel(null)} className="block border-b border-white/[0.06] px-3 py-4"><p className="text-[11px] text-white/65">Equipe jurídica</p><p className="mt-1 text-[10px] text-white/28">Carlos mencionou você na revisão da contestação.</p></Link><p className="px-3 py-5 text-[10px] text-white/24">Nenhuma outra mensagem não lida.</p></> : <><Link href="/painel/juridico/processos?visao=movimentacoes" onClick={() => setPanel(null)} className="block border-b border-white/[0.06] px-3 py-4"><p className="text-[11px] text-white/65">Nova intimação no TRT-2</p><p className="mt-1 text-[10px] text-white/28">Mariana Lopes × Grupo Atlas · há 22 min</p></Link><Link href="/painel/juridico/prazos" onClick={() => setPanel(null)} className="block px-3 py-4"><p className="text-[11px] text-[#ff8175]">2 prazos vencem hoje</p><p className="mt-1 text-[10px] text-white/28">Abra a agenda crítica para revisar.</p></Link></>}</div></section></div> : null}
  </>;
}
